FROM node:16 AS builder

RUN mkdir -p /build
WORKDIR /build

COPY ./package.json yarn.lock /build/

RUN yarn install

COPY ./ /build

RUN yarn run build


# Hack for easily copying built files
FROM scratch AS exporter
COPY --from=builder /build/build .
