name: Build Release

on:
  push:
    branches:
      - "feat/rollup"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build app
        run: bash create_release.sh

      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: 1.0.0
          release_name: Release 1.0.0
          draft: true
          prerelease: false
          body: This release contains version 1.0.0 of the TileBoard app.

      - name: Upload assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./TileBoard.zip
          asset_name: TileBoard.zip
          asset_content_type: application/zip
